import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import {Roboto_Mono } from 'next/font/google'
import NavBar from '@/components/NavBar';


const roboto = Roboto_Mono({ subsets: ["latin" , 'cyrillic'] ,});

export const metadata: Metadata = {
  title: 'Taxi Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    <ClerkProvider>
      <html lang="en">
          <body className={roboto.className}>
            <NavBar />
            {children}
          </body>
      </html>
    </ClerkProvider>
  );
}
